<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>PusherAPI</RootNamespace>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.9" />
		<!-- Transitive package explicitly added to fix vulnerability. Can be removed once upstream packages reference a secure version. -->
		<PackageReference Include="Microsoft.OpenApi" Version="3.7.0" />
		<PackageReference Include="Scalar.AspNetCore" Version="2.16.9" />
	</ItemGroup>

</Project>
